export const routes = {
  login: '/login',
  registerVendor: '/dang-ky-chu-sap',
  dashboard: '/',
  profile: '/profile',
  tours: '/tours',
  tourCreate: '/tours/new',
  tourEdit: '/tours/:tourId/edit',
  media: '/media',
  qr: '/qr',
  qrCreate: '/qr/create',
  qrEdit: '/qr/:id/edit',
  pois: '/pois',
  languages: '/languages',
  users: '/users',
  roles: '/roles',
} as const;
