<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VinhHy.AudioTour.Mobile.Data</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.82" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VinhHy.AudioTour.Mobile.Core\VinhHy.AudioTour.Mobile.Core.csproj" />
  </ItemGroup>

</Project>
